### ISSUE TITLE
Game crashes during launch when cloned with github desktop. Works fine when downloading zip

### ISSUE THREAD

**Issue by PostponingCamel** [ardentryst/ardentryst#21]
When cloning from master repo via zip file, the game works fine, no issues.

However, if I clone the repo via the github desktop app, the loading splash screen progresses to 90ish%, and then displays:
"Ardentryst has experienced an unexpected crash.
You may report the bug on Github" (etc..)
Terminal message upon launch:;
```
    Ardentryst Copyright (C) 2007-2020 Elle Trudgett
    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it
    under certain conditions; for details, see the COPYING file.
An error has occurred.
Traceback (most recent call last):
  File "ardentryst.py", line 4656, in <module>
    main()
  File "ardentryst.py", line 3923, in main
    Data.precache_levels()
  File "D:\Github\Ardentryst\ardentryst\data.py", line 264, in precache_levels
    self.levels[levelfile] = pickle.load(open(os.path.join("Levels", levelfile), "rb"))
ModuleNotFoundError: No module named 'mapping\r'
```
Troubleshooting steps tried: reinstalled my github desktop client, deleted local files and cloned several times via client/zip both, issue remains for client but not for zip.
Bug report:
[bugreport.txt](https://github.com/ardentryst/ardentryst/files/5336517/bugreport.txt)

**Comment by elle-trudgett** [comment]
I think this has something to do with the line endings and the reading format of the levels while being unpickled, are you on Windows? I had the same issue when I was trying to run it on Windows too. I think the level files might have had their line endings changed, or are being processed in an os-incompatible way

**Comment by PostponingCamel** [comment]
Yes, I'm on Win 10.

**Comment by hhirsch** [comment]
Sounds like core.autocrlf is set to true. The added \r is the carriage return added for Windows automatically with that setting by git. So from memory Linux uses line feed \n and Windows uses carriage return line feed \r \n. Seems like python expects \n instead of \r \n but not sure why. Maybe compare the core.autocrlf settings of Desktop and Terminal git and change the desktop settings to the one that works.

**Comment by PostponingCamel** [comment]
@hhirsch Can confirm that your solution fixed the problem. did a fresh clone after changing the setting and game launches without issue.
